# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

# everything defined under here will be deleted before applying the manifests
pre_apply: []

# everything defined under here will be deleted after applying the manifests
post_apply:
- name: coredns
  namespace: kube-system
  kind: configmap
- name: coredns
  namespace: kube-system
  kind: deployment
- name: cluster-dns
  namespace: kube-system
  kind: poddisruptionbudget
- name: coredns
  namespace: kube-system
  kind: service
- name: kube-dns-metrics-bash
  namespace: kube-system
  kind: deployment
- name: kube-dns-metrics
  namespace: kube-system
  kind: deployment
- name: dnsmasq-node
  namespace: kube-system
  kind: daemonset
- name: kube-dns-local
  namespace: kube-system
  kind: service
